### ISSUE TITLE
Fix Review CSS

### ISSUE THREAD

**Issue by AviralJ58** [CaptAlpha/SDHRS#1]
Fix the overall frontend of reviews page for hospitals.

**Comment by CaptAlpha** [comment]
![Uploading image.png…]()

**Comment by CaptAlpha** [comment]
Needs Changes

**Comment by AviralJ58** [comment]
![image](https://user-images.githubusercontent.com/77487252/193432497-bf8bcf9a-939e-4bd0-8623-037d5b57232c.png)
Completed
